from app.models import db, Amenity
# Adds a demo user, you can add other users here if you want
def seed_amenities():
    amenity1 = Amenity(getawayId = 1, amenity = "Wifi")
    amenity2 = Amenity(getawayId = 1, amenity = "Hot Tub")
    amenity3 = Amenity(getawayId = 1, amenity = "Patio")
    amenity4 = Amenity(getawayId = 1, amenity = "Fireplace")
    amenity5 = Amenity(getawayId = 2, amenity = "Wifi")
    amenity6 = Amenity(getawayId = 2, amenity = "Hot Tub")
    amenity7 = Amenity(getawayId = 2, amenity = "Patio")
    amenity8 = Amenity(getawayId = 2, amenity = "Kitchen")
    amenity9 = Amenity(getawayId = 2, amenity = "Fireplace")
    amenity10 = Amenity(getawayId = 3, amenity = "Wifi")
    amenity11 = Amenity(getawayId = 3, amenity = "Hot Tub")
    amenity12 = Amenity(getawayId = 3, amenity = "Patio")
    amenity13 = Amenity(getawayId = 3, amenity = "Kitchen")
    amenity14 = Amenity(getawayId = 3, amenity = "Fireplace")
    amenity15 = Amenity(getawayId = 4, amenity = "Wifi")
    amenity16 = Amenity(getawayId = 4, amenity = "Hot Tub")
    amenity17 = Amenity(getawayId = 4, amenity = "Patio")
    amenity18 = Amenity(getawayId = 4, amenity = "Kitchen")
    amenity19 = Amenity(getawayId = 4, amenity = "Fireplace")
    amenity20 = Amenity(getawayId = 5, amenity = "Wifi")
    amenity21 = Amenity(getawayId = 5, amenity = "Hot Tub")
    amenity22 = Amenity(getawayId = 5, amenity = "Patio")
    amenity23 = Amenity(getawayId = 5, amenity = "Fireplace")
    amenity24 = Amenity(getawayId = 6, amenity = "Wifi")
    amenity25 = Amenity(getawayId = 6, amenity = "Hot Tub")
    amenity26 = Amenity(getawayId = 6, amenity = "Patio")
    amenity27 = Amenity(getawayId = 6, amenity = "Kitchen")
    amenity28 = Amenity(getawayId = 6, amenity = "Fireplace")
    amenity29 = Amenity(getawayId = 7, amenity = "Wifi")
    amenity30 = Amenity(getawayId = 7, amenity = "Hot Tub")
    amenity31 = Amenity(getawayId = 7, amenity = "Patio")
    amenity32 = Amenity(getawayId = 7, amenity = "Kitchen")
    amenity33 = Amenity(getawayId = 7, amenity = "Fireplace")
    amenity34 = Amenity(getawayId = 8, amenity = "Wifi")
    amenity35 = Amenity(getawayId = 8, amenity = "Hot Tub")
    amenity36 = Amenity(getawayId = 8, amenity = "Patio")
    amenity37 = Amenity(getawayId = 8, amenity = "Fireplace")
    amenity38 = Amenity(getawayId = 9, amenity = "Wifi")
    amenity39 = Amenity(getawayId = 9, amenity = "Hot Tub")
    amenity40 = Amenity(getawayId = 9, amenity = "Patio")
    amenity41 = Amenity(getawayId = 9, amenity = "Kitchen")
    amenity42 = Amenity(getawayId = 9, amenity = "Fireplace")
    amenity43 = Amenity(getawayId = 10, amenity = "Wifi")
    amenity44 = Amenity(getawayId = 10, amenity = "Hot Tub")
    amenity45 = Amenity(getawayId = 10, amenity = "Patio")
    amenity46 = Amenity(getawayId = 10, amenity = "Kitchen")
    amenity47 = Amenity(getawayId = 11, amenity = "Wifi")
    amenity48 = Amenity(getawayId = 11, amenity = "Hot Tub")
    amenity49 = Amenity(getawayId = 11, amenity = "Patio")
    amenity50 = Amenity(getawayId = 11, amenity = "Kitchen")
    amenity51 = Amenity(getawayId = 11, amenity = "Fireplace")
    amenity52 = Amenity(getawayId = 12, amenity = "Wifi")
    amenity53 = Amenity(getawayId = 12, amenity = "Hot Tub")
    amenity54 = Amenity(getawayId = 12, amenity = "Kitchen")
    amenity55 = Amenity(getawayId = 12, amenity = "Fireplace")
    amenity56 = Amenity(getawayId = 13, amenity = "Wifi")
    amenity57 = Amenity(getawayId = 13, amenity = "Hot Tub")
    amenity58 = Amenity(getawayId = 13, amenity = "Patio")
    amenity59 = Amenity(getawayId = 13, amenity = "Kitchen")
    amenity60 = Amenity(getawayId = 13, amenity = "Fireplace")
    amenity61 = Amenity(getawayId = 14, amenity = "Wifi")
    amenity62 = Amenity(getawayId = 14, amenity = "Hot Tub")
    amenity63 = Amenity(getawayId = 14, amenity = "Patio")
    amenity64 = Amenity(getawayId = 14, amenity = "Kitchen")
    amenity65 = Amenity(getawayId = 14, amenity = "Fireplace")
    amenity66 = Amenity(getawayId = 15, amenity = "Wifi")
    amenity67 = Amenity(getawayId = 15, amenity = "Hot Tub")
    amenity68 = Amenity(getawayId = 15, amenity = "Kitchen")
    amenity69 = Amenity(getawayId = 15, amenity = "Fireplace")
    db.session.add(amenity1)
    db.session.add(amenity2)
    db.session.add(amenity3)
    db.session.add(amenity4)
    db.session.add(amenity5)
    db.session.add(amenity6)
    db.session.add(amenity7)
    db.session.add(amenity8)
    db.session.add(amenity9)
    db.session.add(amenity10)
    db.session.add(amenity11)
    db.session.add(amenity12)
    db.session.add(amenity13)
    db.session.add(amenity14)
    db.session.add(amenity15)
    db.session.add(amenity16)
    db.session.add(amenity17)
    db.session.add(amenity18)
    db.session.add(amenity19)
    db.session.add(amenity20)
    db.session.add(amenity21)
    db.session.add(amenity22)
    db.session.add(amenity23)
    db.session.add(amenity24)
    db.session.add(amenity25)
    db.session.add(amenity26)
    db.session.add(amenity27)
    db.session.add(amenity28)
    db.session.add(amenity29)
    db.session.add(amenity30)
    db.session.add(amenity31)
    db.session.add(amenity32)
    db.session.add(amenity33)
    db.session.add(amenity34)
    db.session.add(amenity35)
    db.session.add(amenity36)
    db.session.add(amenity37)
    db.session.add(amenity38)
    db.session.add(amenity39)
    db.session.add(amenity40)
    db.session.add(amenity41)
    db.session.add(amenity42)
    db.session.add(amenity43)
    db.session.add(amenity44)
    db.session.add(amenity45)
    db.session.add(amenity46)
    db.session.add(amenity47)
    db.session.add(amenity48)
    db.session.add(amenity49)
    db.session.add(amenity50)
    db.session.add(amenity51)
    db.session.add(amenity52)
    db.session.add(amenity53)
    db.session.add(amenity54)
    db.session.add(amenity55)
    db.session.add(amenity56)
    db.session.add(amenity57)
    db.session.add(amenity58)
    db.session.add(amenity59)
    db.session.add(amenity60)
    db.session.add(amenity61)
    db.session.add(amenity62)
    db.session.add(amenity63)
    db.session.add(amenity64)
    db.session.add(amenity65)
    db.session.add(amenity66)
    db.session.add(amenity67)
    db.session.add(amenity68)
    db.session.add(amenity69)



    db.session.commit()


# Uses a raw SQL query to TRUNCATE the users table.
# SQLAlchemy doesn't have a built in function to do this
# TRUNCATE Removes all the data from the table, and RESET IDENTITY
# resets the auto incrementing primary key, CASCADE deletes any
# dependent entities
def undo_amenities():
    db.session.execute('TRUNCATE amenities RESTART IDENTITY CASCADE;')
    db.session.commit()
