from app.models import db, Getaway


# Adds a demo user, you can add other users here if you want
def seed_getaways():
    getaway1 = Getaway(userId = 1, address = "653 Hidden Valley Rd", city = "Gatlinburg", state = "Tennessee", country = "United States", latitude = 35.73176, longitude = -83.4938, name = "Lookout Loft", price = 292, description = """Lookout Loft is a brand new luxurious cabin with mountain views that you've been dreaming of! Our cabin is located just 3 miles to downtown Gatlinburg. Designed with a 'slow' pace in mind. Our hope is that you enjoy every part of your stay at our cabin; from enjoying your morning cup of coffee to curling up by the fire as the sun sets over the mountains. Our cabin is a cozy place for friends and family to gather for a memorable stay in the mountains!""", numGuests = 4, numBeds=2, numBaths=1, numBedrooms=2,)
    getaway2 = Getaway(userId = 1, address = "211 Parkway, Gatlinburg, TN ", city = "Gatlinburg", state = "Tennessee", country = "United States", latitude = 35.7229, longitude = -83.51026, name = "The King's Cabin", price = 158, description = """The cabin features unbelievable views of Mt. Leconte and The Great Smoky Mountains National Park right off the private deck. If you are looking for a wonderful place to relax, look no further than this cabin. The cabin features a private deck with seating and an amazing hot tub to enjoy the enormous views of the GSMNP! The cabin is an easy 3.6 miles to downtown Gatlinburg, TN! These views rival if not beat any views you can find in Gatlinburg, TN!""", numGuests = 4, numBeds=2, numBaths=1, numBedrooms=2,)
    getaway3 = Getaway(userId = 1, address = "147 Poplar Ln", city = "Gatlinburg", state = "Tennessee", country = "United States", latitude = 35.71748, longitude = -83.50552, name = "Bear Necessities", price = 133, description = """Bear Necessities is a lovely 1 bedroom cabin located just off the parkway (US 441) between Gatlinburg and Pigeon Forge. It is 10-15 minutes from either city and the entrance to the National Park. Romantic setting with Hot Tub contained in a screened-in, covered porch area. Game room with pool table.""", numGuests = 4, numBeds=2, numBaths=1, numBedrooms=2,)
    getaway4 = Getaway(userId = 2, address = "1088 Powdermill Road", city = "Gatlinburg", state = "Tennessee", country = "United States", latitude = 35.75454, longitude = -83.45359, name = "Just the Two of Us", price = 167, description = """5 STAR Sparkling Clean Sanitized Spectacular mountain view/open plan/authentic storybook cabin with black bear theme, 3 mi from downtown Gatlinburg, private, romantic cabin for 2 only. Great honeymoon, anniversary, business or get away from it all. Keurig coffemaker Gas log fireplace,Flat screen TV, Cable, Wifi, Internet, CD player, DVD player, movie selection,charcoal grill, Heart Shaped whirlpool tub overlooks mountains. hot tub, 2 recliner rockers,Comfy King Size bed. No pets/no smoking""", numGuests = 2, numBeds=1, numBaths=1, numBedrooms=1,)
    getaway5 = Getaway(userId = 2, address = "902 Street of Dreams Way", city = "Gatlinburg", state = "Tennessee", country = "United States", latitude = 35.72912, longitude = -83.53458, name = "Mountain Magic", price = 140, description = """1BD/2BA Log cabin with incredible views of the Smokies, and only mins. to dwtn. Gatlinburg. You can see the aerial tram to Ober Gatlinburg,also backs up to the Nat'l Park itself, enjoy the natural beauty of the Smokies. Home includes a large great room w/vaulted ceilings on the main level, recreation room area on the same level,Home also includes a spacious main deck area, hot tub & loft complete with a Master BD and BA w/an in-room whirlpool, as well as a catwalk out to your own private balcony""", numGuests = 4, numBeds=2, numBaths=1, numBedrooms=2,)
    getaway6 = Getaway(userId = 2, address = "1455 East Parkway", city = "Gatlinburg", state = "Tennessee", country = "United States", latitude = 35.7273445129394, longitude = -83.4618530273437, name = "The Mountain Miracle", price = 137, description = """Gorgeous cabin located in Gatlinburg, TN! This cabin sleeps up to 7 guests and features 2 bathrooms! The cabin sits in the famous "Ski Mountain" area of Gatlinburg, TN and is surrounded by large mature trees and gorgeous nature! Enjoy modern touches including a stocked kitchen complete with granite countertops! Come experience this wonderful Gatlinburg cabin today!""", numGuests = 7, numBeds=4, numBaths=2, numBedrooms=3,)
    
    getaway7 = Getaway(userId = 2, address = " 1503 Zermatt Drive", city = "Gatlinburg", state = "Tennessee", country = "United States", latitude = 35.703853, longitude = -83.552345, name = "Mountain Majesty", price = 119, description = """Newly renovated downtown Gatlinburg Condo!!! This condo is just a short .3 mile walk to the heart of downtown Gatlinburg, TN! It offers gorgeous mountain views off the private back porch! The condo features 1 bedroom and 1 bathroom and sleeps up to 4 guests! Guests can enjoy the pool as well as the amazing ability to be able to walk right into downtown Gatlinburg! You can't beat this location! See you soon!""", numGuests = 4, numBeds=2, numBaths=1, numBedrooms=1)
    getaway8 = Getaway(userId = 2, address = "239 East Parkway", city = "Gatlinburg", state = "Tennessee", country = "United States", latitude = 35.7161098, longitude = -83.5087289, name = "Sunset View", price = 275, description = """BRAND NEW! Nestled on top of the Smoky Mountains with breathtaking views. Enjoy our hot tub overlooking the gorgeous landscape with a swivel mounted outdoor tv. Only 4 miles away from downtown Gatlinburg and minutes away from many other attractions including Dollywood, Ober Gatlinburg, Anakeesta, live shows, ect. This one bedroom/1.5 bathroom sleeps 4 with a king bed downstairs and a queen sleeper sofa upstairs! Fast wifi with Netflix, youtube tv and arcade machine included!!!""", numGuests = 4, numBeds=3, numBaths=1, numBedrooms=2,)
    getaway9 = Getaway(userId = 3, address = "122 Parkway", city = "Gatlinburg", state = "Tennessee", country = "United States", latitude = 35.7243468, longitude = -83.5100373, name = "The Chalet", price = 150, description = """Sleeping Beauty is a true log cabin in the heart of Gatlinburg! You’ll love my place because It is so close to so many attractions, Ober Gatlinburg, downtown Gatlinburg but yet secluded in the mountains, the views, the location, the people, the ambiance, the outdoors space. My place is good for couples, solo adventurers, business travelers, and families (with kids) COMMUNITY POOL IS OPEN MEMORIAL DAY TO LABOR DAY""", numGuests = 4, numBeds=2, numBaths=1, numBedrooms=2)
    getaway10 = Getaway(userId = 3, address = "745 Powdermill Road", city = "Gatlinburg", state = "Tennessee", country = "United States", latitude = 35.7243468, longitude = -83.5100373, name = "The Retreat", price = 185, description = """Retreat to the beautiful Smoky Mountains in a brand new construction luxury cabin just 5min away from the attractions in Gatlinburg AND the entrance to Great Smoky Mountain National Park! This cabin is the perfect blend of seclusion and activity, an incredible location that cannot be beat!

    Book your next trip where mountain escape meets luxury getaway!""", numGuests = 4, numBeds=2, numBaths=1, numBedrooms=2)
    getaway11 = Getaway(userId = 3, address = "849 Glades Road", city = "Gatlinburg", state = "Tennessee", country = "United States", latitude = 35.7399559020996, longitude = -83.4612808227539, name = "Mountain Freedom", price = 134, description = """Mountain Freedom"" NEW! Private & Cozy Mountain Retreat for 2! Wi Fi & hot tub!
    Enjoy this quaint and cozy mountain retreat! This lovely cabin will provide you the relaxation you desire with forest views and fresh mountain air. This cabin has a master suite that's ideal for a romantic getaway. Relax in a private hot tub while taking in the sights and sounds of the nature around you. Located close to many area attractions and the Great Smoky Mountains!""", numGuests = 2, numBeds=1, numBaths=1, numBedrooms=1)
    getaway12 = Getaway(userId = 3, address = "410 Ski Mountain Road", city = "Gatlinburg", state = "Tennessee", country = "United States", latitude = 35.7066679, longitude = -83.528095, name = "The Getaway", price = 110, description = """NEW FARMHOUSE RENOVATION!!Gorgeous, modern, totally renovated non-smoking Condo elevated ABOVE Downtown Gatlinburg! Walk to all the action during the day, and return to beautiful views from your private balcony! Imagine those same views that evening while relaxing in your KING sized bed? Summer pool & winter fireplace! 2 BIG Smart TVs and kitchenette. Don't pay $20+ for parking! Leave your car & walk everywhere, catch a trolley or grab a seat on the new double decker local tour bus!""", numGuests = 4, numBeds=2, numBaths=1, numBedrooms=2,)
    getaway13 = Getaway(userId = 3, address = "1441 Wiley Oakley Drive", city = "Gatlinburg", state = "Tennessee", country = "United States", latitude = 35.7096983, longitude = -83.5405047, name = "Moutain Mystic", price = 152, description = """A log cabin for 2 nestled at the end of a private drive, Shooting Star is designed for relaxation and romance. Not only does the gas fireplace, set in rustic stone, warm up the cabin on chilly evenings, but it also bathes the wood-planked walls and beamed ceiling in a romantic glow.""", numGuests = 2, numBeds=1, numBaths=1, numBedrooms=1,)
    getaway14 = Getaway(userId = 3, address = "440 Ski Mountain Road", city = "Gatlinburg", state = "Tennessee", country = "United States", latitude = 35.7065467834472, longitude = -83.5281448364257, name = "Bear Lodge", price = 74, description = """With a bedroom that includes both a heart-shaped Jacuzzi and a fireplace, Magic Moments II is made for romantic getaways. But because the 1-bedroom cabin includes a sofa that converts into a queen-size bed, it’s also a delightful, conveniently located option for a family of up to 4.""", numGuests = 4, numBeds=3, numBaths=1, numBedrooms=2,)
    getaway15 = Getaway(userId = 3, address = "559 Parkway", city = "Gatlinburg", state = "Tennessee", country = "United States", latitude = 35.7132578, longitude = -83.5118663, name = "Wonderful Wilderness", price = 121, description = """Welcome to Condo LeConte! Extraordinary views of The Great Smoky Mountains National Park and downtown Gatlinburg, TN await you at this wonderful condo! The condo is located less than 15 minutes to the middle of downtown Gatlinburg! The condo sleeps 4 guests with a queen bed and queen sleeper sofa. It also features one full bathroom with a tub/shower! The condo complex offers tons of amenities including indoor and outdoor pool as well as indoor hot tub! Come visit today!""", numGuests = 4, numBeds=3, numBaths=1, numBedrooms=2,)
    db.session.add(getaway1)
    db.session.add(getaway2)
    db.session.add(getaway3)
    db.session.add(getaway4)
    db.session.add(getaway5)
    db.session.add(getaway6)
    db.session.add(getaway7)
    db.session.add(getaway8)
    db.session.add(getaway9)
    db.session.add(getaway10)
    db.session.add(getaway11)
    db.session.add(getaway12)
    db.session.add(getaway13)
    db.session.add(getaway14)
    db.session.add(getaway15)
    db.session.commit()


# Uses a raw SQL query to TRUNCATE the users table.
# SQLAlchemy doesn't have a built in function to do this
# TRUNCATE Removes all the data from the table, and RESET IDENTITY
# resets the auto incrementing primary key, CASCADE deletes any
# dependent entities
def undo_getaways():
    db.session.execute('TRUNCATE getaways RESTART IDENTITY CASCADE;')
    db.session.commit()
