"""amenities model.

Revision ID: 8e41ca310b6d
Revises: 1a5d9b143b15
Create Date: 2021-12-15 13:45:58.034105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e41ca310b6d'
down_revision = '1a5d9b143b15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amenities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('getawayId', sa.Integer(), nullable=False),
    sa.Column('amenity', sa.String(length=50), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['getawayId'], ['getaways.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('amenities')
    # ### end Alembic commands ###
