"""relabel_reservation_columns

Revision ID: eef34d5facc1
Revises: 6ae2d2f7df1e
Create Date: 2021-12-15 12:10:22.625594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eef34d5facc1'
down_revision = '6ae2d2f7df1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'profilePictureUrl')
    op.drop_column('reservations', 'lastName')
    op.drop_column('reservations', 'endDate')
    op.drop_column('reservations', 'startDate')
    op.add_column('reservations', sa.Column('startDate', sa.DateTime(), nullable=False))
    op.add_column('reservations', sa.Column('endDate', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('lastName', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('reservations', sa.Column('profilePictureUrl', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
