"""reservation and getawaymodel

Revision ID: 6ae2d2f7df1e
Revises: ffdc0a98111c
Create Date: 2021-12-15 11:15:28.422660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ae2d2f7df1e'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('getaways',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('city', sa.String(length=285), nullable=False),
    sa.Column('state', sa.String(length=285), nullable=False),
    sa.Column('country', sa.String(length=285), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('name', sa.String(length=285), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('getawayId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('startDate', sa.String(length=255), nullable=False),
    sa.Column('endDate', sa.String(length=50), nullable=False),
    sa.Column('lastName', sa.String(length=50), nullable=False),
    sa.Column('profilePictureUrl', sa.String(length=500), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['getawayId'], ['getaways.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('firstName', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('lastName', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('profilePictureUrl', sa.String(length=500), nullable=False))
    op.add_column('users', sa.Column('createdAt', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updatedAt', sa.DateTime(), nullable=True))
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.drop_column('users', 'updatedAt')
    op.drop_column('users', 'createdAt')
    op.drop_column('users', 'profilePictureUrl')
    op.drop_column('users', 'lastName')
    op.drop_column('users', 'firstName')
    op.drop_table('reservations')
    op.drop_table('getaways')
    # ### end Alembic commands ###
