"""empty message

Revision ID: 55098e0fe793
Revises: 5ab2cc7d2a1d
Create Date: 2022-02-22 20:00:04.874575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55098e0fe793'
down_revision = '5ab2cc7d2a1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('imageNumber', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'imageNumber')
    # ### end Alembic commands ###
