"""empty message

Revision ID: 5ab2cc7d2a1d
Revises: 8e41ca310b6d
Create Date: 2022-01-10 11:29:48.701659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ab2cc7d2a1d'
down_revision = '8e41ca310b6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('reservationsId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reviews', 'reservations', ['reservationsId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'reservationsId')
    # ### end Alembic commands ###
