# .github/workflows/app.yaml
name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        S3_BUCKET: ${{ secrets.S3_BUCKET }}
        S3_KEY: ${{ secrets.S3_KEY }}
        S3_SECRET: ${{ secrets.S3_SECRET }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1
      - name: Run Pytest
        run: |
          pipenv install -r requirements.txt
          pipenv run pytest -v
